server:
  port: 11000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nochristmas
    username: root
    password: 1230
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  